### ISSUE TITLE
European Frequencies?

### ISSUE THREAD

**Issue by runahue** [bemasher/rtldavis#8]
Hello friends:

Can we use it with European Frequencies ISS?

Thank's a lot.

**Comment by bemasher** [comment]
You can use it with any frequency your rtl-sdr dongle can tune to. Frequency hopping tables are setup for use with US models. You'll need to fill in the frequencies and hopping order here:
https://github.com/bemasher/rtldavis/blob/master/protocol/protocol.go#L59-L91

This project is no longer maintained, feel free to fork it for your own use.
